# Generated by Django 5.2.5 on 2025-12-22 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('instance_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID da Instância')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token da Instância')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número WhatsApp')),
                ('integration_type', models.CharField(choices=[('WHATSAPP-BAILEYS', 'WhatsApp Baileys'), ('WHATSAPP-BUSINESS', 'WhatsApp Business'), ('EVOLUTION', 'Evolution')], default='WHATSAPP-BAILEYS', max_length=50, verbose_name='Tipo de Integração')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('connected', 'Conectada'), ('disconnected', 'Desconectada'), ('error', 'Erro')], default='created', max_length=20, verbose_name='Status')),
                ('qrcode', models.BooleanField(default=True, verbose_name='Gerar QR Code')),
                ('qrcode_base64', models.TextField(blank=True, null=True, verbose_name='QR Code Base64')),
                ('reject_call', models.BooleanField(default=False, verbose_name='Rejeitar Chamadas')),
                ('msg_call', models.TextField(blank=True, null=True, verbose_name='Mensagem de Chamada')),
                ('groups_ignore', models.BooleanField(default=False, verbose_name='Ignorar Grupos')),
                ('always_online', models.BooleanField(default=False, verbose_name='Sempre Online')),
                ('read_messages', models.BooleanField(default=False, verbose_name='Ler Mensagens')),
                ('read_status', models.BooleanField(default=False, verbose_name='Ler Status')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('webhook_by_events', models.BooleanField(default=False, verbose_name='Webhook por Eventos')),
                ('webhook_base64', models.BooleanField(default=True, verbose_name='Webhook Base64')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
                'ordering': ['-created_at'],
            },
        ),
    ]
