# Generated by Django 5.2.5 on 2025-12-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Número com código do país (ex: 5511999999999)', max_length=20, verbose_name='Destinatário')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo')], default='text', max_length=20, verbose_name='Tipo')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('media_caption', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Resposta da API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instances.instance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-sent_at'],
            },
        ),
    ]
