# Generated by Django 5.2.5 on 2025-12-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('sticker', 'Sticker')], default='text', max_length=20, verbose_name='Tipo'),
        ),
    ]
