# Generated by Django 5.2.5 on 2025-12-22 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_message_media_file_message_media_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('sticker', 'Sticker')], default='text', max_length=20, verbose_name='Tipo')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='campaigns/%Y/%m/%d/', verbose_name='Arquivo')),
                ('media_caption', models.TextField(blank=True, null=True, verbose_name='Legenda')),
                ('media_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total de Destinatários')),
                ('success_count', models.IntegerField(default=0, verbose_name='Enviados com Sucesso')),
                ('error_count', models.IntegerField(default=0, verbose_name='Erros')),
                ('distribuicao_modo', models.CharField(choices=[('imediato', 'Imediato'), ('ate_horario', 'Até Horário'), ('tempo_total', 'Tempo Total')], default='imediato', max_length=20, verbose_name='Modo de Distribuição')),
                ('tempo_estimado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempo Estimado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sending', 'Enviando'), ('completed', 'Concluída'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='instances.instance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instances.campaign', verbose_name='Campanha'),
        ),
    ]
