# Generated by Django 5.2.5 on 2025-12-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_message_created_at_campaign_message_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
