# Generated by Django 5.2.5 on 2025-12-24 02:05

import instances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_campaign_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=instances.models.campaign_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='media_filename',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome do Arquivo'),
        ),
    ]
