# Generated by Django 5.2.5 on 2026-02-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0006_alter_campaign_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('IN', 'Recebida'), ('OUT', 'Enviada')], default='OUT', max_length=3, verbose_name='Direção'),
        ),
        migrations.AddField(
            model_name='message',
            name='wamid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Mensagem (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(help_text='Número com código do país', max_length=30, verbose_name='Destinatário/Remetente'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('number', models.CharField(help_text='Número wa_id (ex: 555183097389)', max_length=30, verbose_name='Número')),
                ('profile_pic', models.URLField(blank=True, null=True, verbose_name='URL da Foto')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Última Mensagem em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='instances.instance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-last_message_at'],
                'unique_together': {('instance', 'number')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='instances.contact', verbose_name='Contato'),
        ),
    ]
